# Generated by Django 5.1.1 on 2024-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores_municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_indicadores_Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_ENT', models.CharField(max_length=10)),
                ('CVE_ENT', models.CharField(max_length=2)),
                ('NOM_ENT', models.CharField(max_length=100)),
                ('Abreviado_Entidad', models.CharField(max_length=2)),
                ('Pob_Ind', models.FloatField()),
                ('GPR_INEGI_T_ENT', models.FloatField()),
                ('GPR_INEGI_H_ENT', models.FloatField()),
                ('GPR_INEGI_M_ENT', models.FloatField()),
                ('PORC_ANALFA_T_ENT', models.FloatField()),
                ('PORC_ANALFA_H_ENT', models.FloatField()),
                ('PORC_ANALFA_M_ENT', models.FloatField()),
                ('PORC_ALEB_20A24_ENT', models.FloatField()),
                ('PORC_ALEMS_20A24_ENT', models.FloatField()),
                ('tasa_asis_3a5_ent', models.FloatField()),
                ('tasa_asis_6a11_ent', models.FloatField()),
                ('tasa_asis_12a14_ent', models.FloatField()),
                ('tasa_asis_15a17_ent', models.FloatField()),
                ('INDIGENA_ENT', models.IntegerField()),
                ('NO_IND_ENT', models.IntegerField()),
                ('POB_TOTAL_ENT', models.IntegerField()),
                ('PORC_IND_ENT', models.FloatField()),
                ('PORC_NO_IND_ENT', models.FloatField()),
                ('HLI_3YMAS_ENT', models.IntegerField()),
                ('NO_HLI_ENT', models.IntegerField()),
                ('NE_HLI_ENT', models.IntegerField()),
                ('POB3YMAS_ENT', models.IntegerField()),
                ('porc_hli_3mas_ENT', models.FloatField()),
                ('porc_no_hli_ENT', models.FloatField()),
                ('porc_ne_hli_ENT', models.FloatField()),
                ('HLI_3mas_espa_ENT', models.IntegerField()),
                ('HLI_3mas_Noespa_ENT', models.IntegerField()),
                ('HLI_3mas_NE_ENT', models.IntegerField()),
                ('porc_hli_3mas_espa_ENT', models.FloatField()),
                ('porc_hii_3mas_Noespa_ENT', models.FloatField()),
                ('Porc_hli_3mas_NE_ENT', models.FloatField()),
                ('HLI_3A5_ENT', models.IntegerField()),
                ('POB_3A5_ENT', models.IntegerField()),
                ('PORC_HLI_3A5_ENT', models.FloatField()),
                ('HLI_6A11_ENT', models.IntegerField()),
                ('POB_6A11_ENT', models.IntegerField()),
                ('PORC_HLI_6A11_ENT', models.FloatField()),
                ('HLI_12A14_ENT', models.IntegerField()),
                ('POB_12A14_ENT', models.IntegerField()),
                ('PORC_HLI_12A14_ENT', models.FloatField()),
                ('HLI_15A17_ENT', models.IntegerField()),
                ('POB_15A17_ENT', models.IntegerField()),
                ('PORC_HLI_15A17_ENT', models.FloatField()),
            ],
        ),
    ]
